### PR TITLE
Update cards.js

### PR DESCRIPTION
**Pull request by Tejasvigupta**
Instead of `if` statement a `while loop` should be used as sometimes even the 2nd random value can be same as the 1st random value.

### CODE REVIEW

**Comment by abhaybhatt** [comment]
@Tejasvigupta i think this while loop will run for ever add some terminating case in it

**Comment by Tejasvigupta** [comment]
```
        setPro1(Math.floor(Math.random() * profiless.length));
        setPro2(Math.floor(Math.random() * profiless.length)); 
```
Here you have set the values for both Pro1 and Pro2.
Now the loop will only go until `Pro1` value is different them `Pro2` value. Once the random `Pro2` values is different form `Pro1` value, the loop will terminate itself.
```
        while(pro1 === pro2){
            setPro2(Math.floor(Math.random() * profiless.length));
        }
```

**Comment by abhaybhatt** [comment]
> ```
>         setPro1(Math.floor(Math.random() * profiless.length));
>         setPro2(Math.floor(Math.random() * profiless.length)); 
> ```
> 
> Here you have set the values for both Pro1 and Pro2.
> Now the loop will only go until `Pro1` value is different them `Pro2` value. Once the random `Pro2` values is different form `Pro1` value, the loop will terminate itself.
> 
> ```
>         while(pro1 === pro2){
>             setPro2(Math.floor(Ma

**Comment by abhaybhatt** [comment]
@Tejasvigupta got it.
Thanks

**Pull request merged**
